spring.application.name=fintech-risk-platform-java

# PostgreSQL database configuration (keep transactional data)
spring.datasource.url=jdbc:postgresql://localhost:5432/fintech_db
spring.datasource.username=postgres
spring.datasource.password=postgresql

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MongoDB configuration (keep logging, audit trail, risk events and analytics data)
spring.mongodb.uri=mongodb://localhost:27017/fintech_mongo_db

# Server configuration
server.port=8080

# JWT configuration
jwt.secret=MySuperSecretJwtKey1234567890123456
jwt.expiration-ms=3600000